import { ExternalLink, Minus, Network, Plus, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { useLibrary } from "../state/LibraryContext";
import type { Paper } from "../types";

type Edge = { from: number; to: number; score: number };
type GraphNode = { paper: Paper; x: number; y: number; color: string; radius: number; opacity: number; label: string; degree: number };
const paperTokens = (paper: Paper) => new Set((paper.titleEn + " " + (paper.titleZh ?? "") + " " + (paper.summary ?? "") + " " + (paper.abstractEn ?? "") + " " + (paper.abstractZh ?? "")).toLowerCase().match(/[a-z0-9]{3,}|[\u4e00-\u9fff]{2,}/g) ?? []);
const overlap = (left: Set<string>, right: Set<string>) => { let count = 0; left.forEach(token => { if (right.has(token)) count++; }); return count / Math.max(1, Math.min(left.size, right.size)); };
const authorYear = (paper: Paper) => { const first = paper.authors[0]?.name?.trim() || "Unknown"; const author = first.split(/[\s,]+/).filter(Boolean).at(-1) || first; const year = paper.publicationDate?.match(/^\d{4}/)?.[0] || "n.d."; return author + ", " + year; };

export function KnowledgeGraph({ onOpenPaper }: { onOpenPaper(paper: Paper): void }) {
  const { data } = useLibrary(); const [query, setQuery] = useState(""); const [threshold, setThreshold] = useState(.24); const [zoom, setZoom] = useState(1); const [selectedId, setSelectedId] = useState<string>();
  const graph = useMemo(() => {
    const papers = (data?.papers ?? []).filter(paper => !paper.deletedAt && (paper.titleEn + " " + (paper.titleZh ?? "") + " " + (paper.summary ?? "")).toLowerCase().includes(query.toLowerCase())).slice(0, 300);
    const colors = new Map((data?.categories ?? []).map(category => [category.id, category.color])); const wordSets = papers.map(paperTokens); const edges: Edge[] = [];
    for (let from = 0; from < papers.length; from++) for (let to = from + 1; to < papers.length; to++) { const sharedTags = papers[from].tagIds.filter(id => papers[to].tagIds.includes(id)).length; const score = Math.min(.55, sharedTags * .24) + (papers[from].categoryId && papers[from].categoryId === papers[to].categoryId ? .14 : 0) + overlap(wordSets[from], wordSets[to]) * .42; if (score >= threshold) edges.push({ from, to, score }); }
    const degree = Array.from({ length: papers.length }, () => 0); edges.forEach(edge => { degree[edge.from] += edge.score; degree[edge.to] += edge.score; });
    const groups = [...new Set(papers.map(paper => paper.categoryId || "unclassified"))]; const nodes: GraphNode[] = papers.map((paper, index) => { const key = paper.categoryId || "unclassified"; const peers = papers.filter(item => (item.categoryId || "unclassified") === key); const order = peers.findIndex(item => item.id === paper.id); const cluster = groups.indexOf(key); const clusterAngle = Math.PI * 2 * cluster / Math.max(1, groups.length); const localAngle = Math.PI * 2 * order / Math.max(1, peers.length); const density = degree[index]; const centerX = 500 + Math.cos(clusterAngle) * 170; const centerY = 330 + Math.sin(clusterAngle) * 125; const localRadius = 38 + (order % 4) * 27 + Math.max(0, 55 - density * 45); return { paper, x: centerX + Math.cos(localAngle) * localRadius, y: centerY + Math.sin(localAngle) * localRadius, color: colors.get(paper.categoryId || "") || "#7666b9", radius: Math.min(50, 14 + Math.sqrt(density + .2) * 19), opacity: Math.min(.96, .48 + density * .38), label: authorYear(paper), degree: density }; });
    return { nodes, edges: edges.sort((left, right) => right.score - left.score).slice(0, 700) };
  }, [data, query, threshold]);
  const selected = graph.nodes.find(node => node.paper.id === selectedId) ?? graph.nodes[0]; const size = 1 / zoom; const offsetX = (1 - size) * 500; const offsetY = (1 - size) * 325;
  return <main className="knowledge-graph-page">
    <header className="knowledge-graph-header"><div><span className="eyebrow"><Network size={14} />LOCAL PAPER MAP</span><h1>本地知识树</h1><p>颜色表示主领域；节点越大、越深，表示与当前资料库中其他论文的关联越多。它是本地相似度图，不是引用网络。</p></div><label className="knowledge-search"><Search size={15} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="筛选论文" /></label></header>
    <div className="knowledge-controls"><label>关系阈值 <input type="range" min=".12" max=".62" step=".02" value={threshold} onChange={event => setThreshold(Number(event.target.value))} /><strong>{Math.round(threshold * 100)}%</strong></label><span>{graph.nodes.length} 篇论文 · {graph.edges.length} 条关联</span></div>
    <div className="knowledge-map-layout"><section className="knowledge-map"><div className="knowledge-zoom"><button onClick={() => setZoom(value => Math.max(.65, value - .15))} title="缩小"><Minus size={17} /></button><strong>{Math.round(zoom * 100)}%</strong><button onClick={() => setZoom(value => Math.min(2.2, value + .15))} title="放大"><Plus size={17} /></button></div><svg viewBox={offsetX + " " + offsetY + " " + 1000 * size + " " + 650 * size} role="img" aria-label="本地论文关系图">{graph.edges.map((edge, index) => <line key={index} x1={graph.nodes[edge.from].x} y1={graph.nodes[edge.from].y} x2={graph.nodes[edge.to].x} y2={graph.nodes[edge.to].y} style={{ strokeWidth: .6 + edge.score * 2.8, opacity: .1 + edge.score * .38 }} />)}{graph.nodes.map(node => <g className={"knowledge-map-node " + (selected?.paper.id === node.paper.id ? "selected" : "")} key={node.paper.id} transform={"translate(" + node.x + " " + node.y + ")"} onClick={() => setSelectedId(node.paper.id)} onDoubleClick={() => onOpenPaper(node.paper)}><circle r={node.radius + 3} fill="transparent" stroke={node.color} strokeOpacity={selected?.paper.id === node.paper.id ? 1 : 0} strokeWidth="3" /><circle r={node.radius} fill={node.color} fillOpacity={node.opacity} /><text y={node.radius + 15}>{node.label}</text><title>{node.paper.titleZh || node.paper.titleEn}</title></g>)}</svg>{!graph.nodes.length && <div className="knowledge-empty">没有可显示的论文。</div>}</section>
      <aside className="knowledge-inspector">{selected ? <><span className="status">本地论文</span><h2>{selected.paper.titleZh || selected.paper.titleEn}</h2>{selected.paper.titleZh && <p className="english-title">{selected.paper.titleEn}</p>}<p>{selected.paper.authors.map(author => author.name).join(", ") || "作者待补充"} · {selected.paper.publicationDate?.slice(0, 4) || "年份待补充"}</p><dl><div><dt>局部关联强度</dt><dd>{Math.round(selected.degree * 100)}%</dd></div><div><dt>一句话总结</dt><dd>{selected.paper.summary || "待补充"}</dd></div></dl><button className="primary" onClick={() => onOpenPaper(selected.paper)}><ExternalLink size={15} />在论文表格中定位</button><small>单击节点查看；双击节点直接在论文表格中打开。</small></> : <p>单击节点查看论文信息。</p>}</aside>
    </div>
  </main>;
}

