import { useState } from "react";
import { Globe2, LoaderCircle } from "lucide-react";
import { backend } from "../services/backend";
import type { OnlineMetadataCandidate, Paper } from "../types";
import { now, uuid } from "../types";

export function OnlineMetadataFillButton({ paper, onSave }: { paper: Paper; onSave(paper: Paper): Promise<void> }) {
  const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  const lookup = async () => { setBusy(true); try { const result = await backend.lookupOnlineMetadata(paper.id); if (!result.candidates.length) { setNotice("Crossref 未找到可用候选。"); return; } const choice = result.candidates.length === 1 ? 1 : Number(window.prompt("请选择要应用的候选编号：\n" + result.candidates.map((item, index) => (index + 1) + ". " + (item.titleEn ?? "无标题") + (item.doi ? "\n   DOI: " + item.doi : "")).join("\n"), "1")); const candidate = result.candidates[choice - 1]; if (!candidate) return; await apply(candidate); } catch (error) { setNotice(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); } };
  const apply = async (candidate: OnlineMetadataCandidate) => { const titleEn = candidate.titleEn && candidate.titleEn !== paper.titleEn && window.confirm("用 Crossref 候选标题覆盖当前英文标题？\n\n" + candidate.titleEn) ? candidate.titleEn : paper.titleEn; const next: Paper = { ...paper, titleEn, authors: paper.authors.length ? paper.authors : candidate.authors.map(name => ({ id: uuid(), name })), abstractEn: paper.abstractEn || candidate.abstractEn, venue: paper.venue || candidate.venue, publicationDate: paper.publicationDate || candidate.publicationDate, doi: paper.doi || candidate.doi, sourceUrl: paper.sourceUrl || candidate.sourceUrl, updatedAt: now() }; const changes = [!paper.authors.length && next.authors.length ? "作者" : "", !paper.abstractEn && next.abstractEn ? "英文摘要" : "", !paper.venue && next.venue ? "期刊/会议" : "", !paper.publicationDate && next.publicationDate ? "日期" : "", !paper.doi && next.doi ? "DOI" : "", !paper.sourceUrl && next.sourceUrl ? "链接" : ""].filter(Boolean); if (!changes.length && next.titleEn === paper.titleEn) { setNotice("候选没有可补全的新字段。"); return; } if (!window.confirm("将应用：" + (changes.join("、") || "英文标题") + "。除英文标题外，已有字段不会被覆盖。继续吗？")) return; await onSave(next); setNotice("已应用 Crossref 元数据：" + (changes.join("、") || "英文标题") + "。"); };
  return <span className="online-metadata-action"><button className="secondary" disabled={busy} onClick={() => void lookup()}>{busy ? <LoaderCircle className="spin" size={16} /> : <Globe2 size={16} />}查找在线元数据</button>{notice && <small>{notice}</small>}</span>;
}
