import { useMemo, useState } from "react";
import { createColumnHelper, flexRender, getCoreRowModel, getSortedRowModel, useReactTable, type SortingState } from "@tanstack/react-table";
import { ExternalLink, FileText, Heart, Trash2 } from "lucide-react";
import type { Category, Paper, Tag } from "../types";

const statusLabel = { unread: "\u672a\u8bfb", reading: "\u5728\u8bfb", read: "\u5df2\u8bfb", archived: "\u5df2\u5f52\u6863" };
const helper = createColumnHelper<Paper>();

export function PaperTable({ papers, categories, tags, selectedId, onSelect, onOpenPdf, onToggleFavorite, onBulkRecycle }: { papers: Paper[]; categories: Category[]; tags: Tag[]; selectedId?: string; onSelect(paper: Paper): void; onOpenPdf(paper: Paper): void; onToggleFavorite(paper: Paper): void; onBulkRecycle(papers: Paper[]): void }) {
  const [sorting, setSorting] = useState<SortingState>([{ id: "updatedAt", desc: true }]);
  const [checkedIds, setCheckedIds] = useState<Set<string>>(new Set());
  const selectedPapers = papers.filter(paper => checkedIds.has(paper.id));
  const toggle = (id: string) => setCheckedIds(current => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; });
  const toggleAll = () => setCheckedIds(current => current.size === papers.length ? new Set() : new Set(papers.map(paper => paper.id)));
  const columns = useMemo(() => [
    helper.display({ id: "select", header: () => <input className="row-check" type="checkbox" aria-label="\u5168\u9009\u8bba\u6587" checked={papers.length > 0 && checkedIds.size === papers.length} ref={element => { if (element) element.indeterminate = checkedIds.size > 0 && checkedIds.size < papers.length; }} onClick={event => event.stopPropagation()} onChange={toggleAll} />, size: 40, enableSorting: false, cell: info => <input className="row-check" type="checkbox" aria-label="\u9009\u62e9\u8bba\u6587" checked={checkedIds.has(info.row.original.id)} onClick={event => event.stopPropagation()} onChange={() => toggle(info.row.original.id)} /> }),
    helper.accessor("favorite", { id: "favorite", header: "", size: 38, enableSorting: true, cell: info => <button className={`favorite ${info.getValue() ? "on" : ""}`} onClick={event => { event.stopPropagation(); onToggleFavorite(info.row.original); }} aria-label="\u6536\u85cf"><Heart size={15} fill={info.getValue() ? "currentColor" : "none"} /></button> }),
    helper.accessor("titleEn", { id: "title", header: "\u8bba\u6587\u9898\u76ee", size: 330, cell: info => <div className="title-cell"><strong>{info.row.original.titleZh || info.getValue()}</strong>{info.row.original.titleZh && <small>{info.getValue()}</small>}</div> }),
    helper.accessor("authors", { header: "\u4f5c\u8005", size: 150, cell: info => <span className="ellipsis">{info.getValue().map(author => author.name).join(", ") || "—"}</span> }),
    helper.accessor("status", { header: "\u72b6\u6001", size: 84, cell: info => <span className={`status status-${info.getValue()}`}>{statusLabel[info.getValue()]}</span> }),
    helper.accessor("categoryId", { header: "\u9886\u57df", size: 130, cell: info => { const category = categories.find(item => item.id === info.getValue()); return category ? <span className="category" style={{ "--tag-color": category.color } as React.CSSProperties}>{category.name}</span> : <span className="muted">\u672a\u5206\u7c7b</span>; } }),
    helper.accessor("tagIds", { header: "\u6807\u7b7e", size: 175, enableSorting: false, cell: info => { const items = tags.filter(tag => info.getValue().includes(tag.id)); return <div className="tags">{items.slice(0, 2).map(tag => <span key={tag.id} style={{ "--tag-color": tag.color } as React.CSSProperties}>{tag.name}</span>)}{items.length > 2 && <small>+{items.length - 2}</small>}</div>; } }),
    helper.accessor("summary", { header: "\u4e00\u53e5\u8bdd\u603b\u7ed3", size: 280, cell: info => <span className="ellipsis muted-strong" title={info.getValue()}>{info.getValue() || "\u5f85\u8865\u5145"}</span> }),
    helper.accessor("venue", { header: "\u671f\u520a / \u4f1a\u8bae", size: 110, cell: info => info.getValue() || "—" }),
    helper.accessor("publicationDate", { header: "\u53d1\u5e03\u65e5\u671f", size: 110, cell: info => info.getValue()?.slice(0, 10) || "—" }),
    helper.accessor("updatedAt", { header: "\u6700\u8fd1\u66f4\u65b0", size: 115, cell: info => new Date(info.getValue()).toLocaleDateString("zh-CN") }),
    helper.display({ id: "links", header: "\u94fe\u63a5", size: 84, cell: info => <div className="row-actions">{info.row.original.sourceUrl && <button title="\u6253\u5f00\u539f\u6587" onClick={event => { event.stopPropagation(); window.open(info.row.original.sourceUrl, "_blank"); }}><ExternalLink size={15} /></button>}<button title={info.row.original.pdfPath ? "\u6253\u5f00 PDF" : "\u672a\u5173\u8054 PDF"} disabled={!info.row.original.pdfPath} onClick={event => { event.stopPropagation(); onOpenPdf(info.row.original); }}><FileText size={16} /></button></div> })
  ], [categories, checkedIds, onOpenPdf, onToggleFavorite, papers.length, tags]);
  const table = useReactTable({ data: papers, columns, state: { sorting }, onSortingChange: setSorting, getCoreRowModel: getCoreRowModel(), getSortedRowModel: getSortedRowModel(), columnResizeMode: "onChange" });
  const recycleSelected = () => { if (!selectedPapers.length || !confirm(`\u5c06 ${selectedPapers.length} \u7bc7\u8bba\u6587\u53ca\u5176\u53d7\u7ba1 PDF \u79fb\u5165\u56de\u6536\u7ad9\uff1f`)) return; onBulkRecycle(selectedPapers); setCheckedIds(new Set()); };
  return <div className="table-scroll">{selectedPapers.length > 0 && <div className="table-bulk-actions"><strong>\u5df2\u9009 {selectedPapers.length} \u7bc7</strong><button className="secondary danger" onClick={recycleSelected}><Trash2 size={15} />\u79fb\u5165\u56de\u6536\u7ad9</button><button className="ghost" onClick={() => setCheckedIds(new Set())}>\u53d6\u6d88\u9009\u62e9</button></div>}<table className="paper-table" style={{ width: table.getCenterTotalSize() }}><thead>{table.getHeaderGroups().map(group => <tr key={group.id}>{group.headers.map(header => <th key={header.id} style={{ width: header.getSize() }} onClick={header.column.getToggleSortingHandler()}>{flexRender(header.column.columnDef.header, header.getContext())}{header.column.getIsSorted() && <small>{header.column.getIsSorted() === "asc" ? " ↑" : " ↓"}</small>}<span className="resize-handle" onMouseDown={header.getResizeHandler()} onTouchStart={header.getResizeHandler()} /></th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(row => <tr key={row.id} className={`${selectedId === row.original.id ? "selected" : ""} ${checkedIds.has(row.original.id) ? "checked" : ""}`} onClick={() => onSelect(row.original)} onDoubleClick={() => onOpenPdf(row.original)}>{row.getVisibleCells().map(cell => <td key={cell.id} style={{ width: cell.column.getSize() }}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</tr>)}</tbody></table>{papers.length === 0 && <div className="table-empty">\u5f53\u524d\u89c6\u56fe\u6ca1\u6709\u8bba\u6587</div>}</div>;
}
