import { useState } from "react";
import { Archive, Database, Download, HardDrive, Laptop, LockKeyhole, Palette, RotateCcw, Save, ShieldCheck, Sparkles, Tags as TagsIcon, UserRound } from "lucide-react";
import { backend, isTauri } from "../services/backend";
import { useLibrary } from "../state/LibraryContext";
import type { Category, Profile, Tag } from "../types";
import { uuid } from "../types";

import { LlmSettingsForm } from "./LlmSettingsForm";
import { OnlineMetadataSettingsForm } from "./OnlineMetadataSettingsForm";
export function SettingsView() {
  const { data, saveProfile, saveCategory, saveTag, mergeTaxonomy, refresh } = useLibrary(); const [section, setSection] = useState("profile"); const [notice, setNotice] = useState("");
  if (!data) return null; const sections = [{ id: "profile", label: "个人资料", icon: UserRound }, { id: "llm", label: "LLM 自动整理", icon: Sparkles }, { id: "metadata", label: "在线元数据", icon: Database }, { id: "taxonomy", label: "分类与标签", icon: TagsIcon }, { id: "data", label: "本地数据", icon: HardDrive }, { id: "privacy", label: "隐私与安全", icon: ShieldCheck }];
  return <main className="settings-page"><header className="page-heading"><div><h1>设置</h1><p>管理个人偏好、本地资料目录和数据安全。</p></div></header><div className="settings-layout"><nav>{sections.map(({ id, label, icon: Icon }) => <button key={id} className={section === id ? "active" : ""} onClick={() => setSection(id)}><Icon size={16} />{label}</button>)}</nav><section className="settings-content">
    {section === "profile" && <ProfileForm profile={data.profile} onSave={async profile => { await saveProfile(profile); setNotice("个人资料已保存"); }} />}
    {section === "llm" && <LlmSettingsForm />}
    {section === "metadata" && <OnlineMetadataSettingsForm />}
    {section === "taxonomy" && <TaxonomyManager categories={data.categories} tags={data.tags} saveCategory={saveCategory} saveTag={saveTag} mergeTaxonomy={mergeTaxonomy} />}
    {section === "data" && <><h2><Database size={19} />本地资料库</h2><p className="settings-description">数据库、PDF、框架图和批注均保存在以下目录。</p><div className="path-box"><HardDrive size={18} /><code>{data.libraryPath}</code></div><div className="relocation-note"><strong>资料库位置</strong><p>选择一个目标文件夹后，应用会完整复制资料库并在下次启动切换；旧副本会保留。</p><button className="secondary" onClick={async () => { if (!isTauri()) { setNotice("浏览器预览模式不能迁移资料库"); return; } if (!confirm("将复制当前资料库到所选文件夹，并在下次启动切换。旧副本不会删除，继续吗？")) return; const next = await backend.chooseLibraryLocation(); if (next) setNotice("资料库已复制到：" + next + "。请关闭并重新打开应用以切换。"); }}>选择新的资料库位置</button></div><div className="settings-actions"><button className="primary" onClick={async () => { const path = await backend.backup(); setNotice(path ? `备份已创建：${path}` : "浏览器预览模式不创建 ZIP 备份"); }}><Archive size={16} />创建完整备份</button><button className="secondary" onClick={async () => { if (await backend.restore()) { await refresh(); setNotice("备份恢复完成"); } }}><RotateCcw size={16} />从备份恢复</button></div><div className="info-card"><Save size={18} /><div><strong>自动保存已开启</strong><p>论文字段和批注会立即写入 SQLite；原始 PDF 永不被覆写。</p></div></div></>}
    {section === "privacy" && <><h2><ShieldCheck size={19} />隐私与安全</h2><div className="privacy-grid"><article><Laptop /><strong>单机单用户</strong><p>不需要账号，不连接云同步服务。</p></article><article><LockKeyhole /><strong>最小文件权限</strong><p>桌面端只访问受管资料目录和你明确选择的文件。</p></article><article><Download /><strong>无后台联网</strong><p>不含遥测、广告或自动元数据请求。</p></article></div><p className="warning-note">V1 不提供数据库或备份加密。Windows 用户账户权限是默认访问边界。</p></>}
    {notice && <div className="settings-notice">{notice}</div>}
  </section></div></main>;
}

function ProfileForm({ profile, onSave }: { profile: Profile; onSave(value: Profile): Promise<void> }) { const [value, setValue] = useState(profile); return <form className="settings-form" onSubmit={e => { e.preventDefault(); void onSave(value); }}><h2><UserRound size={19} />个人资料</h2><p className="settings-description">仅用于本机界面展示，不会上传。</p><label>显示名<input value={value.displayName} onChange={e => setValue(v => ({ ...v, displayName: e.target.value }))} /></label><label>研究方向<input value={value.researchField} onChange={e => setValue(v => ({ ...v, researchField: e.target.value }))} placeholder="例如：计算机视觉 / 推荐系统" /></label><label><Palette size={15} />主题<select value={value.theme} onChange={e => setValue(v => ({ ...v, theme: e.target.value as Profile["theme"] }))}><option value="system">跟随系统</option><option value="light">浅色</option><option value="dark">深色</option></select></label><button className="primary"><Save size={16} />保存个人资料</button></form>; }

function TaxonomyManager({ categories, tags, saveCategory, saveTag, mergeTaxonomy }: { categories: Category[]; tags: Tag[]; saveCategory(v: Category): Promise<void>; saveTag(v: Tag): Promise<void>; mergeTaxonomy(kind: "category"|"tag", source: string, target?: string): Promise<void> }) { const add = async (kind: "category"|"tag") => { const name = prompt(kind === "category" ? "新领域名称" : "新标签名称"); if (!name) return; const value = { id: uuid(), name, color: "#7867c6" }; kind === "category" ? await saveCategory(value) : await saveTag(value); }; return <><h2><TagsIcon size={19} />分类与标签</h2><div className="taxonomy-section"><header><div><strong>Category</strong><small>每篇论文最多选择一个主领域</small></div><button className="secondary" onClick={() => add("category")}>新增领域</button></header><div className="taxonomy-list">{categories.map(item => <article key={item.id}><i style={{ background: item.color }} /><span>{item.name}</span><button onClick={async () => { const name = prompt("重命名", item.name); if (name) await saveCategory({ ...item, name }); }}>编辑</button><button onClick={() => confirm(`删除“${item.name}”？相关论文将变为未分类。`) && mergeTaxonomy("category", item.id)}>删除</button></article>)}</div></div><div className="taxonomy-section"><header><div><strong>Tags</strong><small>用于补充方法、任务与阅读用途</small></div><button className="secondary" onClick={() => add("tag")}>新增标签</button></header><div className="taxonomy-list">{tags.map(item => <article key={item.id}><i style={{ background: item.color }} /><span>{item.name}</span><button onClick={async () => { const name = prompt("重命名", item.name); if (name) await saveTag({ ...item, name }); }}>编辑</button><button onClick={() => confirm(`删除标签“${item.name}”？`) && mergeTaxonomy("tag", item.id)}>删除</button></article>)}</div></div></>; }
